### ISSUE TITLE
--citra option can't handle comments

### ISSUE THREAD

**Issue by smesgr9000** [SabreTools/NDecrypt#13]
on Version 0.2.5 on linux

```
$ strace ./NDecrypt d --citra ~/test.3ds
```

part of my aes_keys.text
```
generator=12345
# Some usefull comment
slot0x18KeyX=12345
```

according to strace the first generator line was read but than stopped on the file
if I remove the comment. The file is read as expected.

I think the following change could fix the issue, but can't test due to not having a Visual Studio setup atm.
```
                    while (reader.ReadNextLine())
                    {
                        if (reader.KeyValuePair == null || string.IsNullOrWhiteSpace(reader.KeyValuePair?.Key))
                            break; // replace the break with continue;```

**Comment by mnadareski** [comment]
Strictly speaking, lines with `#` at the start are not treated as comments in INI files. That being said, I can try to handle that case for nonstandard INIs like the one you have.

**Comment by smesgr9000** [comment]
thanks for looking into this. What makes you think this is an INI file? The documentation of the file is rather limited, but if you have a look at the CITA source code they clearly handle "#" stuff.  See Line 221 https://github.com/citra-emu/citra/blob/cbe898703631b404dfc430a60050fd8d0956a62f/src/core/hw/aes/key.cpp#L221
