### ISSUE TITLE
-c Flag Unavailable

### ISSUE THREAD

**Issue by MrMendelli** [SabreTools/NDecrypt#6]
I want to decrypt some dumped titles for use with Citra. The [readme](https://github.com/SabreTools/NDecrypt/blob/master/README.md) states the flag `-c, --citra` can be used for this, but is is not a valid input when used, and does not show up when running from the commandline to list help:

![Untitled](https://user-images.githubusercontent.com/47702158/153774187-1897ae7f-49e9-4f74-9f26-1ae84001a278.png)

This is happening with build 0.2.2.

**Comment by mnadareski** [comment]
It's available in the latest WIP build. It's not in the last stable.

**Comment by MrMendelli** [comment]
Thanks for the update. I don't see it in releases so I presume it's yet to be publicly available?
