### ISSUE TITLE
Wrong usage for --hash flag is displayed after decryption

### ISSUE THREAD

**Issue by mariomadproductions** [SabreTools/NDecrypt#8]
If you use the --hash / -h flag but don't provide a path afterwards, the program only tells you of your error after the decryption/encryption is completed. And by then, the program has already read the file, so calculating the hash would take double the time. Only a minor thing, but still.

**Comment by mariomadproductions** [comment]
Yeah, I think I provided it at the end.

**Comment by mnadareski** [comment]
Proper usage, as copied from the README: `NDecrypt.exe <operation> [flags] <path> ...`

**Comment by mariomadproductions** [comment]
Usually command line programs allow variable orders, but okay np.
